const api = (path, options = {}) => fetch(`/api/v1${path}`, { headers: { "Content-Type": "application/json" }, ...options }).then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error?.code || "request_failed"); return data; });
const esc = value => String(value ?? "").replace(/[&<>"']/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
const formatBytes = value => value > 1e9 ? `${(value / 1e9).toFixed(1)} GB` : `${(value / 1e6).toFixed(0)} MB`;
async function loadModels() {
  const { models } = await api("/models");
  document.querySelector("#models").innerHTML = models.map(model => `<article class="card"><h3>${esc(model.id)}</h3><div class="meta">${esc(model.license.id)} · ${formatBytes(model.size_bytes)} · ${esc(model.runtime)}</div><div class="progress" aria-label="安装进度"><i style="width:${Math.round(model.progress * 100)}%"></i></div><div class="meta">状态：${esc(model.state)} · ${Math.round(model.progress * 100)}%</div><button data-model="${esc(model.id)}" ${model.state === "ready" || model.state === "downloading" ? "disabled" : ""}>${model.state === "awaiting_license" ? "接受许可证并安装" : "安装 / 修复"}</button></article>`).join("");
  document.querySelectorAll("[data-model]").forEach(button => button.addEventListener("click", async () => { button.disabled = true; document.querySelector("#model-live").textContent = "安装任务已启动"; await api(`/models/${button.dataset.model}/install`, { method:"POST", body:JSON.stringify({accept_license:true}) }); await loadModels(); }));
}
async function loadJobs() { const { jobs } = await api("/jobs?limit=50"); document.querySelector("#jobs").innerHTML = jobs.length ? jobs.map(job => `<div class="job"><div><strong>${esc(job.source.display_locator)}</strong><br><small>${esc(job.id)} · ${esc(job.artifacts.map(a => a.kind).join(" / ") || "暂无产物")}</small></div><span class="status">${esc(job.state)}${job.degraded ? " · degraded" : ""}</span></div>`).join("") : "<p class='hint'>还没有任务。</p>"; }
async function loadSettings() { const { settings } = await api("/settings"); document.querySelector("#enable-bilibili").checked = !!settings.enable_bilibili; document.querySelector("#enable-remote-text").checked = !!settings.enable_remote_text; }
document.addEventListener("DOMContentLoaded", async () => { try { const health = await api("/health"); document.querySelector("#health").textContent = `在线 · ${health.version}`; await Promise.all([loadModels(), loadJobs(), loadSettings()]); } catch (error) { document.querySelector("#health").textContent = "服务不可用"; }
  document.querySelector("#refresh").addEventListener("click", () => loadJobs());
  document.querySelector("#job-form").addEventListener("submit", async event => { event.preventDefault(); const kind = document.querySelector("#source-kind").value; const locator = document.querySelector("#source-locator").value; const result = document.querySelector("#submit-result"); try { const probe = await api("/sources/probe", { method:"POST", body:JSON.stringify({kind,locator}) }); if (!confirm(`确认加入：${probe.source.title || probe.source.display_locator || "该来源"}？`)) return; await api("/jobs", { method:"POST", body:JSON.stringify({items:[{source:{kind,locator}}]}) }); result.textContent = "已加入队列"; event.target.reset(); await loadJobs(); } catch (error) { result.textContent = `未提交：${error.message}`; } });
  document.querySelector("#save-settings").addEventListener("click", async () => { const result = document.querySelector("#settings-result"); try { await api("/settings", { method:"PATCH", body:JSON.stringify({enable_bilibili:document.querySelector("#enable-bilibili").checked, enable_remote_text:document.querySelector("#enable-remote-text").checked}) }); result.textContent = "设置已保存；需要重启的适配器将在下一次启动生效。"; } catch (error) { result.textContent = `保存失败：${error.message}`; } });
});
